/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8VnHrLlwqSW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { Button } from "@/components/ui/button"
import Link from "next/link"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"
import React from "react"

export function Home() {
  return (
    (<React.Fragment>
      <div className="flex flex-col h-screen">
        <header
          className="bg-white shadow-sm px-4 py-2 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <Button className="rounded-full" size="icon" variant="ghost">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
            <nav className="hidden md:flex items-center space-x-4">
              <Link className="text-sm font-medium hover:underline" href="#" prefetch={false}>
                Home
              </Link>
              <Link className="text-sm font-medium hover:underline" href="#" prefetch={false}>
                Equity Research
              </Link>
              <Link className="text-sm font-medium hover:underline" href="#" prefetch={false}>
                Market Research
                <DropdownMenu>
                  <DropdownMenuContent>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Ghana Fintech Landscape Report
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Mobile Money Adoption Trends
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Regulatory Landscape for Fintechs
                      </Link>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </Link>
              <Link className="text-sm font-medium hover:underline" href="#" prefetch={false}>
                Financial Articles
                <DropdownMenu>
                  <DropdownMenuContent>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        The Rise of Mobile Money in Ghana
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Fintech Regulations in Ghana
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        The Future of Fintech in Ghana
                      </Link>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                Podcast
                <DropdownMenu>
                  <DropdownMenuContent>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Episode 1: The Rise of Mobile Money
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Episode 2: Fintech Regulations in Ghana
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Link href="#" prefetch={false}>
                        Episode 3: The Future of Fintech in Ghana
                      </Link>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </Link>
            </nav>
          </div>
          <div className="flex items-center space-x-4">
            <div className="relative flex items-center">
              <Avatar className="h-8 w-8 mr-2">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>LA</AvatarFallback>
              </Avatar>
              <Input
                className="pl-8 pr-8"
                placeholder="How can I find information about a Ghanaian listed company?" />
            </div>
            <Link className="text-sm font-medium hover:underline" href="#" prefetch={false}>
              <DropdownMenu>
                <DropdownMenuTrigger>Speak to our analyst</DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem>Book an Analyst</DropdownMenuItem>
                  <DropdownMenuItem>Send us an email</DropdownMenuItem>
                  <DropdownMenuItem>Get direction to our office</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </Link>
          </div>
        </header>
        <section
          className="bg-gradient-to-r from-[#0c1b2b] to-[#0a1423] py-12 px-6 flex flex-col items-center justify-center flex-1 relative">
          <h1 className="text-4xl font-bold text-white mb-4">Welcome to The Libinance Podcast App</h1>
          <p className="text-lg text-gray-200 mb-8">Explore the world of finance at your fingertips.</p>
          <div className="flex space-x-4">
            <Button
              className="bg-white text-gray-900 hover:bg-gray-200"
              size="lg"
              variant="solid">
              Get Started
            </Button>
            <Button
              className="text-white hover:bg-white hover:text-gray-900"
              size="lg"
              variant="outline">
              Learn More
            </Button>
          </div>
        </section>
        <section className="bg-gray-100 py-6 px-4">
          <h2 className="text-xl font-bold mb-4">Real-Time Stock Prices</h2>
          <div className="flex space-x-4 overflow-x-auto">
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>MTNGH</strong>- GHS 0.75
                </p>
                <div className="text-green-500 font-bold text-sm">+2.5%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>TULLOW</strong>- GHS 2.50
                </p>
                <div className="text-red-500 font-bold text-sm">-1.2%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>UNIL</strong>- GHS 12.00
                </p>
                <div className="text-green-500 font-bold text-sm">+0.8%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GOIL</strong>- GHS 7.25
                </p>
                <div className="text-red-500 font-bold text-sm">-0.5%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>SOGEGH</strong>- GHS 3.80
                </p>
                <div className="text-green-500 font-bold text-sm">+1.3%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>BOPP</strong>- GHS 18.50
                </p>
                <div className="text-red-500 font-bold text-sm">-0.7%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>TOTAL</strong>- GHS 5.90
                </p>
                <div className="text-green-500 font-bold text-sm">+1.1%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GGBL</strong>- GHS 1.50
                </p>
                <div className="text-green-500 font-bold text-sm">+0.7%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>AYRTN</strong>- GHS 0.25
                </p>
                <div className="text-red-500 font-bold text-sm">-1.0%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>ECOBANK</strong>- GHS 0.80
                </p>
                <div className="text-green-500 font-bold text-sm">+1.5%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GGBL</strong>- GHS 2.00
                </p>
                <div className="text-red-500 font-bold text-sm">-0.5%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>AYRTN</strong>- GHS 1.00
                </p>
                <div className="text-green-500 font-bold text-sm">+0.8%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>TOTAL</strong>- GHS 0.60
                </p>
                <div className="text-red-500 font-bold text-sm">-0.3%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>ECOBANK</strong>- GHS 0.90
                </p>
                <div className="text-green-500 font-bold text-sm">+1.2%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GGBL</strong>- GHS 2.20
                </p>
                <div className="text-red-500 font-bold text-sm">-0.9%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>BOPP</strong>- GHS 8.00
                </p>
                <div className="text-green-500 font-bold text-sm">+1.0%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>SOGEGH</strong>- GHS 5.50
                </p>
                <div className="text-red-500 font-bold text-sm">-0.6%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GOIL</strong>- GHS 2.80
                </p>
                <div className="text-green-500 font-bold text-sm">+0.9%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>UNILEVER</strong>- GHS 4.00
                </p>
                <div className="text-red-500 font-bold text-sm">-0.8%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>AYRTN</strong>- GHS 1.80
                </p>
                <div className="text-green-500 font-bold text-sm">+1.1%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>TOTAL</strong>- GHS 0.40
                </p>
                <div className="text-red-500 font-bold text-sm">-0.5%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>ECOBANK</strong>- GHS 1.20
                </p>
                <div className="text-green-500 font-bold text-sm">+0.8%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>TOTAL</strong>- GHS 0.70
                </p>
                <div className="text-red-500 font-bold text-sm">-0.4%</div>
              </CardContent>
            </Card>
            <Card className="min-w-[150px]">
              <CardContent className="flex flex-col items-center justify-center">
                <p className="text-gray-500 text-sm">
                  <strong>GGBL</strong>- GHS 1.90
                </p>
                <div className="text-green-500 font-bold text-sm">+1.0%</div>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="bg-white py-8 px-6">
          <h2 className="text-2xl font-bold mb-4">The Libinance Podcast</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardContent>
                <img
                  alt="Podcast Cover"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Episode 1: The Rise of Mobile Money</h3>
                  <p className="text-gray-500 mb-4">
                    Explore the impact of mobile money on financial inclusion in Ghana.
                  </p>
                  <div className="flex justify-between items-center">
                    <Button variant="link">Listen Now</Button>
                    <Button variant="solid">Subscribe</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Podcast Cover"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Episode 2: Fintech Regulations in Ghana</h3>
                  <p className="text-gray-500 mb-4">Understand the regulatory landscape for fintech in Ghana.</p>
                  <div className="flex justify-between items-center">
                    <Button variant="link">Listen Now</Button>
                    <Button variant="solid">Subscribe</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Podcast Cover"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Episode 3: The Future of Fintech in Ghana</h3>
                  <p className="text-gray-500 mb-4">
                    Explore the emerging trends and innovations in the Ghanaian fintech industry.
                  </p>
                  <div className="flex justify-between items-center">
                    <Button variant="link">Listen Now</Button>
                    <Button variant="solid">Subscribe</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="flex justify-end mt-4">
            <Button className="flex items-center" variant="link">
              View more
              <ArrowRightIcon className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </section>
        <section className="bg-white py-8 px-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold">Equity Research</h2>
            <Button variant="solid">
              <SearchIcon className="h-5 w-5 mr-2" />
              Search
            </Button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">MTN Ghana</h3>
                <p className="text-gray-500 mb-4">Telecom</p>
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-gray-500">Target Price</p>
                    <p className="font-bold">GHS 1.20</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Recommendation</p>
                    <p className="font-bold text-green-500">Buy</p>
                    <Button variant="link">View Research</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">Tullow Oil</h3>
                <p className="text-gray-500 mb-4">Energy</p>
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-gray-500">Target Price</p>
                    <p className="font-bold">GHS 3.00</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Recommendation</p>
                    <p className="font-bold text-yellow-500">Hold</p>
                    <Button variant="link">View Research</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">Unilever Ghana</h3>
                <p className="text-gray-500 mb-4">Consumer Goods</p>
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-gray-500">Target Price</p>
                    <p className="font-bold">GHS 15.00</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Recommendation</p>
                    <p className="font-bold text-green-500">Buy</p>
                    <Button variant="link">View Research</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="bg-gray-100 py-8 px-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold">Market Research</h2>
            <Button variant="solid">
              <SearchIcon className="h-5 w-5 mr-2" />
              Search
            </Button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">Ghana Fintech Landscape Report</h3>
                <p className="text-gray-500 mb-4">Comprehensive analysis of the Ghanaian fintech industry.</p>
                <Button variant="solid">
                  Download
                  <ArrowDownIcon className="ml-2 h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">Mobile Money Adoption Trends</h3>
                <p className="text-gray-500 mb-4">Insights into the growth and usage of mobile money in Ghana.</p>
                <Button variant="solid">
                  Download
                  <ArrowDownIcon className="ml-2 h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <h3 className="text-lg font-bold mb-2">Regulatory Landscape for Fintechs</h3>
                <p className="text-gray-500 mb-4">
                  Understanding the regulatory environment for fintech companies in Ghana.
                </p>
                <Button variant="solid">
                  Download
                  <ArrowDownIcon className="ml-2 h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
          </div>
          <div className="flex justify-end mt-4">
            <Button className="flex items-center" variant="link">
              View more
              <ArrowRightIcon className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </section>
        <section className="bg-white py-8 px-6">
          <h2 className="text-2xl font-bold mb-4">Financial Articles</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardContent>
                <img
                  alt="Article Image"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">The Rise of Mobile Money in Ghana</h3>
                  <p className="text-gray-500 mb-4">Exploring the impact of mobile money on financial inclusion.</p>
                  <Button variant="link">Read More</Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Article Image"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Fintech Regulations in Ghana</h3>
                  <p className="text-gray-500 mb-4">Understanding the regulatory landscape for fintech companies.</p>
                  <Button variant="link">Read More</Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Article Image"
                  className="rounded-t-lg"
                  height={200}
                  src="/placeholder.svg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  width={300} />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">The Future of Fintech in Ghana</h3>
                  <p className="text-gray-500 mb-4">
                    Explore the emerging trends and innovations in the Ghanaian fintech industry.
                  </p>
                  <Button variant="link">Read More</Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="bg-gray-900 text-white py-6 px-4">
          <div className="container mx-auto flex justify-between items-center">
            <p className="text-sm">© 2024 Libinance. All rights reserved.</p>
            <div className="flex space-x-4">
              <Link className="hover:underline" href="#" prefetch={false}>
                Terms of Service
              </Link>
              <Link className="hover:underline" href="#" prefetch={false}>
                Privacy Policy
              </Link>
              <Link className="hover:underline" href="#" prefetch={false}>
                Contact Us
              </Link>
            </div>
          </div>
        </section>
      </div>
      <div
        className="fixed bottom-4 right-4 bg-white shadow-lg rounded-full flex items-center px-6 py-2">
        <div className="flex items-center">
          <Button className="rounded-full" size="icon" variant="ghost">
            <ArrowRightIcon className="h-6 w-6" />
            <span className="sr-only">Ask Libinance AI</span>
          </Button>
          <div className="ml-2 flex items-center">
            <Input
              className="bg-[#0f172a] rounded-full pr-8 pl-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 font-bold text-white"
              placeholder="Ask Libinance AI" />
            <Button className="ml-2 rounded-full" size="icon" variant="solid">
              <SendIcon className="h-5 w-5" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
        </div>
      </div>
    </React.Fragment>)
  );
}

function ArrowDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}
